#!/bin/sh

# /* Copyright (C) 2010, Cybernetica AS, http://www.cybernetica.eu/ */

if [ -z "$CONFROOT" ]; then
  CONFROOT=/var/www/tuvastaja/configurator
fi
if [ -z "$VARDIR" ]; then
  VARDIR=/var/www/tuvastaja/data/conf
fi

# Include functions
. $CONFROOT/functions.sh

DOM=`cat $VAR_DOMAIN`
DNS=`cat $VAR_NAMESERVERS`

RESOLV=/etc/resolv.conf

echo "search $DOM" > $RESOLV
for i in $DNS; do
  echo "nameserver $i" >> $RESOLV
done
echo "lookup file bind" >> $RESOLV
