# $OpenBSD: Makefile,v 1.54 2009/08/16 13:31:27 rui Exp $

VERSION=		4.6.5
COMMENT =		S4A CA software 
DISTNAME =		s4a-ca-${VERSION}

CATEGORIES =		cyber
HOMEPAGE =		http://www.cyber.ee
MAINTAINER =		Cybernetica AS, www.cyber.ee	

PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

#MASTER_SITES =		http://ondatra.cyber.ee/~sven/	
MASTER_SITES =		http://ondatra.cyber.ee/~mattu/tuvastaja/

PATCH_DIST_STRIP =	-p0

PREFIX=/usr/local

WRKDIST =		${WRKDIR}

.include <bsd.port.mk>
