--- Generated by http://www.rcs-comp.com/site/index.php/view/Utilities-SQLite_foreign_key_trigger_generator

-- Copyright (C) 2010, Cybernetica AS, http://www.cybernetica.eu/

-- Foreign Key Preventing insert
CREATE TRIGGER fki_Tuvastaja_tuvastaja_org_Organisation_sid
BEFORE INSERT ON [Tuvastaja]
FOR EACH ROW BEGIN
  SELECT RAISE(ROLLBACK, 'insert on table "Tuvastaja" violates foreign key constraint "fki_Tuvastaja_tuvastaja_org_Organisation_sid"')
  WHERE NEW.tuvastaja_org IS NOT NULL AND (SELECT sid FROM Organisation WHERE sid = NEW.tuvastaja_org) IS NULL;
END;

-- Foreign key preventing update
CREATE TRIGGER fku_Tuvastaja_tuvastaja_org_Organisation_sid
BEFORE UPDATE ON [Tuvastaja]
FOR EACH ROW BEGIN
    SELECT RAISE(ROLLBACK, 'update on table "Tuvastaja" violates foreign key constraint "fku_Tuvastaja_tuvastaja_org_Organisation_sid"')
      WHERE NEW.tuvastaja_org IS NOT NULL AND (SELECT sid FROM Organisation WHERE sid = NEW.tuvastaja_org) IS NULL;
END;

-- Foreign key preventing delete
CREATE TRIGGER fkd_Tuvastaja_tuvastaja_org_Organisation_sid
BEFORE DELETE ON Organisation
FOR EACH ROW BEGIN
  SELECT RAISE(ROLLBACK, 'delete on table "Organisation" violates foreign key constraint "fkd_Tuvastaja_tuvastaja_org_Organisation_sid"')
  WHERE (SELECT tuvastaja_org FROM Tuvastaja WHERE tuvastaja_org = OLD.sid) IS NOT NULL;
END;

-- Foreign Key Preventing insert
CREATE TRIGGER fki_Certificate_cert_tuvastaja_Tuvastaja_sid
BEFORE INSERT ON [Certificate]
FOR EACH ROW BEGIN
  SELECT RAISE(ROLLBACK, 'insert on table "Certificate" violates foreign key constraint "fki_Certificate_cert_tuvastaja_Tuvastaja_sid"')
  WHERE NEW.cert_tuvastaja IS NOT NULL AND (SELECT sid FROM Tuvastaja WHERE sid = NEW.cert_tuvastaja) IS NULL;
END;

-- Foreign key preventing update
CREATE TRIGGER fku_Certificate_cert_tuvastaja_Tuvastaja_sid
BEFORE UPDATE ON [Certificate]
FOR EACH ROW BEGIN
    SELECT RAISE(ROLLBACK, 'update on table "Certificate" violates foreign key constraint "fku_Certificate_cert_tuvastaja_Tuvastaja_sid"')
      WHERE NEW.cert_tuvastaja IS NOT NULL AND (SELECT sid FROM Tuvastaja WHERE sid = NEW.cert_tuvastaja) IS NULL;
END;

-- Foreign key preventing delete
CREATE TRIGGER fkd_Certificate_cert_tuvastaja_Tuvastaja_sid
BEFORE DELETE ON Tuvastaja
FOR EACH ROW BEGIN
  SELECT RAISE(ROLLBACK, 'delete on table "Tuvastaja" violates foreign key constraint "fkd_Certificate_cert_tuvastaja_Tuvastaja_sid"')
  WHERE (SELECT cert_tuvastaja FROM Certificate WHERE cert_tuvastaja = OLD.sid) IS NOT NULL;
END;
