#!/bin/sh

# /* Copyright (C) 2010, Cybernetica AS, http://www.cybernetica.eu/ */

if [ -z "$CONFROOT" ]; then
  CONFROOT=/var/www/tuvastaja/configurator
fi
if [ -z "$VARDIR" ]; then
  VARDIR=/var/www/tuvastaja/data/conf
fi

# Include functions
. $CONFROOT/functions.sh

if [ ! -f $VAR_SNMP_SERVER ]; then 
  echo "127.0.0.1" > $VAR_SNMP_SERVER
fi
SNMP=`cat $VAR_SNMP_SERVER`

if [ ! -f $VAR_CENTRALSERVER ]; then
  CONFSERVER=""
else
  CONFSERVER=`cat $VAR_CENTRALSERVER`
fi

if [ ! -f $VAR_HOSTNAME ]; then
  $D --title "$TITLE" --msgbox "$NOHOSTDOM" 15 50 
  exit 1
fi

if [ ! -f $VAR_DOMAIN ]; then
  $D --title "$TITLE" --msgbox "$NOHOSTDOM" 15 50
  exit 1
fi

HOST=`cat $VAR_HOSTNAME`
DOM=`cat $VAR_DOMAIN`
FQDN="$HOST.$DOM"
NRPECFG=/etc/nrpe.local.cfg

# Setting up static nrpe.cfg
cp $CONFROOT/static/nrpe.cfg /etc/nrpe.cfg

# Default $NRPECFG consists of line: allowed_hosts=127.0.0.1.
if [ -n "$SNMP" ]; then
  if [ "$SNMP" != "127.0.0.1" ]; then
    echo "allowed_hosts=127.0.0.1,$SNMP" > $NRPECFG
  else
    echo "allowed_hosts=127.0.0.1" > $NRPECFG
  fi
else
  echo "allowed_hosts=127.0.0.1" > $NRPECFG
fi

if [ -n "$CONFSERVER" ]; then
  echo "command[check_dns]=/usr/local/libexec/nagios/check_dns  -H $CONFSERVER" >> $NRPECFG
else
  echo "command[check_dns]=/usr/local/libexec/nagios/check_dns  -H $FQDN" >> $NRPECFG
fi

# Create user if it doesn't exist
create_daemon_user _nrpe 556

if ! grep -q -R "nrped" /etc/rc.local; then
  cat /etc/rc.local | sed -e "s/^echo '.'$//g" > /tmp/rc.local
  mv /tmp/rc.local /etc/rc.local
  echo "if [ -x /usr/local/sbin/nrpe ]; then" >> /etc/rc.local
  echo "        echo -n ' nrped';       /usr/local/sbin/nrpe -d -c /etc/nrpe.cfg" >> /etc/rc.local
  echo "fi" >> /etc/rc.local
  echo "echo '.'" >> /etc/rc.local
fi
