#!/bin/sh

# /* Copyright (C) 2010, Cybernetica AS, http://www.cybernetica.eu/ */

if [ -z "$CONFROOT" ]; then
  CONFROOT=/var/www/tuvastaja/configurator
fi
if [ -z "$VARDIR" ]; then
  VARDIR=/var/www/tuvastaja/data/conf
fi

# Include functions
. $CONFROOT/functions.sh

if [ ! -f $VAR_SNMP_SERVER ]; then 
  echo "127.0.0.1" > $VAR_SNMP_SERVER
fi
SNMP=`cat $VAR_SNMP_SERVER`

if [ ! -f $VAR_CENTRALSERVER ]; then
  echo "www.cert.ee" > $VAR_CENTRALSERVER
fi
CONFSERVER=`cat $VAR_CENTRALSERVER`
NRPECFG=/etc/nrpe.local.cfg

# Setting up static nrpe.cfg
cp $CONFROOT/static/nrpe.cfg /etc/nrpe.cfg

# Setting up default $NRPECFG
if [ ! -s $NRPECFG ]; then
  cp $CONFROOT/static/nrpe.local.cfg $NRPECFG
fi

# Default $NRPECFG consists of line: allowed_hosts=127.0.0.1.
if [ -n "$SNMP" ]; then
  if [ "$SNMP" != "127.0.0.1" ]; then
    echo "allowed_hosts=127.0.0.1,$SNMP" > $NRPECFG
  else
    echo "allowed_hosts=127.0.0.1" > $NRPECFG
  fi
else
  echo "allowed_hosts=127.0.0.1" > $NRPECFG
fi

if [ -n "$CONFSERVER" ]; then
  echo "command[check_dns]=/usr/local/libexec/nagios/check_dns  -H $CONFSERVER" >> $NRPECFG
else
  echo "command[check_dns]=/usr/local/libexec/nagios/check_dns  -H www.cert.ee" >> $NRPECFG
fi

# Create user if it doesn't exist
create_daemon_user _nrpe 556

if ! grep -q -R "nrped" /etc/rc.local; then
  echo "if [ -x /usr/local/sbin/nrpe ]; then" >> /etc/rc.local
  echo "        echo -n ' nrped';       /usr/local/sbin/nrpe -d -c /etc/nrpe.cfg" >> /etc/rc.local
  echo "fi" >> /etc/rc.local
fi
