#!/bin/sh

# /* Copyright (C) 2010, Cybernetica AS, http://www.cybernetica.eu/ */


if [ -z "$CONFROOT" ]; then
  CONFROOT=/var/www/tuvastaja/configurator
fi
if [ -z "$VARDIR" ]; then
  VARDIR=/var/www/tuvastaja/data/conf
fi

# Include functions
. $CONFROOT/functions.sh

OSVER=`uname -r`
PATCHLEVEL=`cat /var/www/tuvastaja/updater/status/patchlevel`

echo "$OSVER.$PATCHLEVEL" > $VAR_SOFTWARE_VERSION
